/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MuriloViola (https://sketchfab.com/MuriloViola)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fall-guys-fc86f6c5d5be4a228649e7b790e099ba
title: Fall Guys
*/

import React, { useRef } from 'react'
import { Center, useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fallGuys.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={1} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.defaultMat_2} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.defaultMat_1} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/fallGuys.gltf')
