/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/guy.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={39.6}
        position={[-591.9, 226.71, 1429.34]}
        rotation={[0.08, 1.14, 0]}
        scale={[1, 1, 1]}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -2, 0]} scale={[0.9, 0.9, 0.9]}>
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={nodes.Cube003_2.material} />
        <mesh geometry={nodes.Cube003_3.geometry} material={nodes.Cube003_3.material} />
        <mesh geometry={nodes.Cube003_4.geometry} material={nodes.Cube003_4.material} />
        <mesh geometry={nodes.Cube003_5.geometry} material={nodes.Cube003_5.material} />
        <mesh geometry={nodes.Cube003_6.geometry} material={nodes.Cube003_6.material} />
        <mesh geometry={nodes.Cube003_7.geometry} material={nodes.Cube003_7.material} />
        <mesh geometry={nodes.Cube003_8.geometry} material={nodes.Cube003_8.material} />
        <mesh geometry={nodes.Cube003_9.geometry} material={nodes.Cube003_9.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/guy.gltf')
